name: Update Now Page

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Replace placeholder with last commit date
        run: |
          LAST_UPDATED=$(git log -1 --format=%cs)
          sed -i "s/%%LAST_UPDATED%%/$LAST_UPDATED/" now.html

      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git commit -am "Update last updated date" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
